global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.0.115:9090

  - job_name: "jaeger" # Corrected indentation
    static_configs:
      - targets: ["192.168.0.115:14269"]
